config/routes.rb
Rails.application.routes.draw do
  get 'homes/index'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  devise_scope :user do
    post '/users/passkey_authenticate', to: 'users/sessions#passkey_authenticate'
  end

  resources :posts, only: [:index, :new, :create] do
    collection do
      get :index, defaults: { format: 'html' }
      get :index, defaults: { format: 'csv' }
    end
  end

  resources :passkeys, only: [:new, :create, :index, :destroy] do
    post 'callback', on: :collection
  end

  # Define root path
  root to: 'homes#index'
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/index.html.erb
<!-- app/views/homes/index.html.erb -->
<!-- app/views/homes/index.html.erb -->
<div class="container-top-page" style="background-image: url(<%= asset_path 'background.jpg' %>);">
  <header class="page-header">
    <h1 class="page-title">「嫌われる勇気」実践アプリ</h1>
    <p class="page-subtitle">〜クイズにこたえて、アドラー心理学 ”課題の分離” を練習できます〜</p>
  </header>

  <main class="main-content">
    <section class="cta-section">
      <%= button_to "今すぐ試してみる", new_post_path, method: :get, class: "try-button" %>
    </section>

    <section class="user-section">
      <% if user_signed_in? %>
        <div class="user-name">
          Welcome, <%= current_user.nickname %>さん！
          <%= link_to "Passkeys設定はこちら", passkeys_path %>
        </div>
      <% else %>
        <div class="user-name">
          <%= link_to "ログイン", new_user_session_path %> してください
        </div>
      <% end %>
    </section>

    <section class="info-section">
      <h2>対象者</h2>
      <p>① ベストセラー「嫌われる勇気」を実践したい人</p>
      <p>② 自分の内面を成長させたい人</p>
    </section>

    <section class="info-section">
      <h2>使うタイミング</h2>
      <p>嫌な気持ちになったとき</p>
    </section>

    <section class="info-section">
      <h2>使い方</h2>
      <p>ログインして新規投稿ボタンをクリック</p>
    </section>
      <div class="image-exp">
        <p>サンプル①  新規投稿画面</p>
      </div>
    <div class="image-group">
        <%= image_tag("phone-new1.png", class:"first-image") %>
    </div>
      <div class="image-exp">
        <p>サンプル②  投稿一覧画面</p>
      </div>
    <div class="image-group">
        <%= image_tag("phone-index1.png", class:"second-image") %>
    </div>

  </main>
</div>