config/routes.rb
Rails.application.routes.draw do
  get 'homes/index'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  devise_scope :user do
    post '/users/passkey_authenticate', to: 'users/sessions#passkey_authenticate'
  end

  resources :posts, only: [:index, :new, :create] do
    collection do
      get :index, defaults: { format: 'html' }
      get :index, defaults: { format: 'csv' }
    end
  end

  resources :passkeys, only: [:new, :create, :index, :destroy] do
    post 'callback', on: :collection
  end

  # Define root path
  root to: 'homes#index'
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<%# app/views/layouts/application.html.erb  ヘッダーとメニュバーとフッター%>
<!DOCTYPE html>
<html>
  <head>
    <title>SelfRef</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <% if controller.controller_name == 'sessions' || controller.controller_name == 'registrations' %>
      <%= stylesheet_link_tag "devise", "data-turbo-track": "reload" %>
       <%# if とその次の行は、devise専用CSSの読み込みを設定している %>
    <% end %>
    <%= stylesheet_link_tag "style", "data-turbo-track": "reload" %>
    <%= javascript_import_module_tag "helpers/webauthn_helper" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h3 class="grid-6"><a href="/">Self Reflection</a></h3>
        <% if user_signed_in? %>
        <div class="user_nav grid-6">
        <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class: "header-link" %>
        <%= link_to "新規投稿", new_post_path, class: "header-link" %>
        <%= link_to "投稿一覧", posts_path, class: "header-link" %>
        </div>
        <% else %>
        <div class="grid-6">
        <%= link_to "ログイン", new_user_session_path, class: "header-link" %>
        <%= link_to "新規登録", new_user_registration_path, class: "header-link" %>
        </div>
        <% end %>
      </div>
    </header>

    <div class="body__container">
      <%= yield %>
    </div>
  
   <footer class="footer">
      <p>
        © All rights reserved by SymTr 2024.
      </p>
    </footer>
  </body>
</html>